# Generated by Django 3.1.7 on 2021-04-03 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialist_sector', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('about_me', models.TextField(max_length=100)),
                ('chamber_address', models.TextField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('doctor_image', models.ImageField(blank=True, null=True, upload_to='uploads/doctor_images/')),
                ('join_date', models.DateTimeField(auto_now_add=True)),
                ('specialist_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctor.doctorcategory')),
            ],
        ),
    ]
