# Generated by Django 3.1.7 on 2021-04-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorinformation',
            name='join_date',
        ),
        migrations.AlterField(
            model_name='doctorinformation',
            name='about_me',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='doctorinformation',
            name='chamber_address',
            field=models.TextField(max_length=1000),
        ),
    ]
