# Generated by Django 3.1.7 on 2021-04-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0005_auto_20210411_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryaddress',
            name='address',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='zip_code',
            field=models.IntegerField(),
        ),
    ]
