# Generated by Django 3.1.7 on 2021-04-12 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0007_remove_deliveryaddress_receiver_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='deliveryaddress',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
