# Generated by Django 3.1.7 on 2021-04-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0010_auto_20210413_0238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='last_name',
            new_name='city',
        ),
        migrations.AddField(
            model_name='customer',
            name='division',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='DeliveryAddress',
        ),
    ]
