# Generated by Django 3.1.7 on 2021-04-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=200)),
                ('description', models.TextField()),
                ('blogImage', models.ImageField(blank=True, null=True, upload_to='', verbose_name='uploads/blog_images/')),
                ('uploadDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
