# Generated by Django 3.1.7 on 2021-04-15 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210402_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartblog',
            name='slug',
            field=models.SlugField(max_length=500, unique=True),
        ),
    ]
