# Generated by Django 3.1.7 on 2021-04-12 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0008_auto_20210413_0238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted')], default='Pending', max_length=100),
        ),
    ]
