# Generated by Django 3.1.7 on 2021-04-15 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0009_auto_20210413_0256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('Packed', 'Packed'), ('Accepted', 'Accepted'), ('On The Way', 'On The Way')], default='Pending', max_length=100),
        ),
    ]
