# Generated by Django 3.1.7 on 2021-04-15 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('useraccount', '0012_deliveryaddress'),
        ('ecoshop', '0010_auto_20210415_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderplaced',
            name='address',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='useraccount.deliveryaddress'),
        ),
        migrations.AddField(
            model_name='orderplaced',
            name='payment_method',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Delivered', 'Delivered'), ('On The Way', 'On The Way'), ('Packed', 'Packed'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel')], default='Pending', max_length=100),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='product_category',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='product_description',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='product_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='productdetails',
            name='product_price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
