# Generated by Django 3.1.7 on 2021-04-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0013_auto_20210416_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Cancel', 'Cancel'), ('Delivered', 'Delivered'), ('Accepted', 'Accepted'), ('On The Way', 'On The Way')], default='Pending', max_length=100),
        ),
    ]
