# Generated by Django 3.1.7 on 2021-04-15 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0014_auto_20210416_0257'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_sub_category', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Packed', 'Packed'), ('Cancel', 'Cancel'), ('Accepted', 'Accepted')], default='Pending', max_length=100),
        ),
        migrations.AddField(
            model_name='productdetails',
            name='product_sub_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='ecoshop.productsubcategory'),
        ),
    ]
