# Generated by Django 3.1.7 on 2021-04-15 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0015_auto_20210416_0306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Packed', 'Packed'), ('Accepted', 'Accepted'), ('Delivered', 'Delivered'), ('On The Way', 'On The Way'), ('Cancel', 'Cancel')], default='Pending', max_length=100),
        ),
    ]
