# Generated by Django 3.1.7 on 2021-04-15 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0016_auto_20210416_0306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdetails',
            name='product_sub_category',
        ),
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Accepted', 'Accepted'), ('Cancel', 'Cancel'), ('Packed', 'Packed'), ('On The Way', 'On The Way'), ('Delivered', 'Delivered')], default='Pending', max_length=100),
        ),
    ]
