# Generated by Django 3.1.7 on 2021-04-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoshop', '0018_auto_20210416_0312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('On The Way', 'On The Way'), ('Delivered', 'Delivered'), ('Packed', 'Packed'), ('Accepted', 'Accepted'), ('Cancel', 'Cancel')], default='Pending', max_length=100),
        ),
    ]
